### ISSUE TITLE
[FEATURE] Add language config / protect permission / Folia support

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Pozzoo/QuickWaystones#1]
Can we add a protect permission like other player cannot destroy other player's waypoint?
Also add a language config and folia support plz :>

**Comment by Pozzoo** [comment]
Hello! I have implemented the owner protection and language config! And I'll evaluate making a folia port

**Comment by xiaoyueyoqwq** [comment]
> Hello! I have implemented the owner protection and language config! And I'll evaluate making a folia port

Thanks for your hard working
